name: test
on:
  pull_request: {}
  push:
    branches: [main, "feat/**"]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.3'
          cache-dependency-path: server/go.sum
      - name: go test
        working-directory: server
        run: go test ./... -count=1 -timeout 120s
